export default {
    START_VELOCITY: 2.5,
    ACCELERATION: 0.01,
    VERTICAL_VELOCITY: 10 * 60,
    GRAVITY: 4 * 60,
    FRAMERATE: 60,
    CANVASWIDTH: '100',
    CANVASHEIGHT: '100',


    ROCKETCORN_SIZE: 100,
    START_LIVES: 1,
    COINS_FOR_NEW_LIFE: 10,
    INVULNERABILITY_TIME: 2,

    MAX_NAME_LENGTH: 4,

    SPAWN_OBSTACLES_EVERY_SEC: 2,
    SPAWN_PICKUPS_EVERY_SEC: 1.2,

    POWERUP_SLOWDOWN: 0.75,
    POWERUP_INVULNERABILITY_DURATION: 6,

    POWERUPS: [ 'OFCE', 'VSN', 'ALX', 'BAC', 'TRSL' ],
    OBSTACLES: [ 'feindbild1', 'feindbild2', 'feindbild3' ],

    REST_URL: 'http://happy-css.com/unicore-scores/'
};
